version: "3.1" 
services:
  nginx:
    image: nginx:latest
    ports:
      - 8002:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./www:/var/www/:delegated
    depends_on:
      - php
  php:
    build: .
    container_name: php
    ports:
      - "8001:80"
    volumes:
        - ./www:/var/www/:delegated
    depends_on:
        - db
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
      - ./conf:/etc/mysql/conf.d/
      - persistent:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: 'db'
      PMA_PORT: '3306'
      PMA_USER: 'user'
      PMA_PASSWORD: 'password'
    depends_on:
      - db
volumes:
  persistent: