version: "3.1" 
services:
  www:
    build: .
    container_name: html
    ports:
      - "8001:80"
    volumes:
        - ./html:/var/www/html/
    depends_on:
        - db
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/
      - ./conf:/etc/mysql/conf.d/
      - persistent:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: 'db'
      PMA_PORT: '3306'
      PMA_USER: 'user'
      PMA_PASSWORD: 'password'
    depends_on:
      - db
volumes:
  persistent: