SET time_zone = "+08:00";

CREATE TABLE `myDb`.`Users` (
    `userId` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `account` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE = InnoDB;

CREATE TABLE `myDb`.`Rooms` (
    `roomId` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `roomName` VARCHAR(255) NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `equipment` VARCHAR(255) NOT NULL,
    `capacity` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE = InnoDB;

CREATE TABLE `myDb`.`Records` (
    `recordId` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `roomId` INT UNSIGNED NOT NULL,
    `userId` INT UNSIGNED NOT NULL,
    `numOfPeople` INT NOT NULL,
    `timestampFrom` TIMESTAMP NOT NULL,
    `timestampTo` TIMESTAMP NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`roomId`) REFERENCES Rooms(`roomId`),
    FOREIGN KEY (`userId`) REFERENCES Users(`userId`)
) ENGINE = InnoDB;